### ISSUE TITLE
chromedriver 2.22 not working with Chrome 54+

### ISSUE THREAD

**Issue by stephandrab** [nkbt/nightwatch-autorun#158]
See https://bugs.chromium.org/p/chromedriver/issues/detail?id=1451

Could you update your chromedriver-dependency to the newest one?
https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by nkbt** [comment]
Yeah, it is now updated, I need to publish a new version

**Comment by nkbt** [comment]
Published `nightwatch-autorun@3.1.0`
