### ISSUE TITLE
browser.url() and webpack historyApiFallback

### ISSUE THREAD

**Issue by jlc467** [nkbt/nightwatch-autorun#50]
I used react-component-template and nightwatch-autorun successfully with react-router hashHistory, but when i switched to browserHistory i can't seem to access any routes except '/' using nightwatch's browser.url(). 

E.g. with hashHistory `browser.url('http://localhost:8080/#/myRoute')` works, but browserHistory and `browser.url('http://localhost:8080/myRoute')` gives `Cannot GET /myRoute` error. 

I am sure webpack config has appropriate historyApiFallback and confirmed it works in development mode (`npm run start`)

```
  devServer: {
    hot: true,
    historyApiFallback: {
      index: 'index.html',
      rewrites: [
        { from: /\/myRoute/, to: '/index.html'}
      ]
    },
```

I am sure nightwatch-autorun is using this webpack config with historyApiFallback.

Uncertain if this is related to nightwatch-autorun, but not sure where else to start.

Considering using http://nightwatchjs.org/api/execute.html and using some of the `window.history` functions to change route to see if that will work.

**Comment by nkbt** [comment]
That's strange, I did not have this issue. We have tests on different urls. That must be some app config issue, I guess

**Comment by jlc467** [comment]
Definitely some app config issue. To handle index redirects, I ditched webpack's historyApiFallback option in favor of telling express directly to redirect `*` to my main page. Now i can change routes with nightwatch successfully. Thx.

**Comment by nkbt** [comment]
Cheers! Happy you found and fixed it!
